import React, { useState } from 'react';
import { 
  Sparkles, 
  X, 
  Brain, 
  HelpCircle, 
  Layers, 
  Calculator, 
  ArrowRight, 
  CheckCircle2, 
  RefreshCw,
  Award
} from 'lucide-react';
import type { LMSLesson } from '../data/curriculumData';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  currentLesson: LMSLesson;
}

export const AiWidgetsModal: React.FC<Props> = ({
  isOpen,
  onClose,
  currentLesson
}) => {
  const [activeTool, setActiveTool] = useState<"explainer" | "mcq" | "flashcards" | "credit">("explainer");
  const [explainerTopic, setExplainerTopic] = useState(currentLesson.title);
  const [explanationResult, setExplanationResult] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState<boolean>(false);

  // Credit calculator state
  const [best6Avg, setBest6Avg] = useState<number>(85);
  const [capstoneScore, setCapstoneScore] = useState<number>(90);

  if (!isOpen) return null;

  const handleGenerateExplanation = () => {
    setIsGenerating(true);
    setTimeout(() => {
      setExplanationResult(
        `### AI Concept Breakdown: ${explainerTopic}\n\n` +
        `**Key Principle:** In the context of Viksit Bharat @2047, ${explainerTopic} bridges theoretical research with commercial execution through structured prototyping and IPR protection.\n\n` +
        `**Key Milestones:**\n` +
        `1. **Hypothesis Formulation:** Define measurable problem statements without premature solution bias.\n` +
        `2. **TRL Progression:** Transition from TRL 3 (Proof of Concept) to TRL 6 (System Prototype Demonstration).\n` +
        `3. **Venture Viability:** Calibrate unit economics (CAC vs LTV) and file provisional patents to establish early priority dates.\n\n` +
        `*Generated by NCIE Shiksha AI Engine using official AICTE/NCIE syllabus repository.*`
      );
      setIsGenerating(false);
    }, 600);
  };

  // Calculate composite score
  const finalCalculatedScore = Math.round(0.25 * best6Avg + 0.75 * capstoneScore);
  const isCreditEligible = best6Avg >= 40 && capstoneScore >= 40;

  return (
    <div className="nptel-modal-backdrop" onClick={onClose}>
      <div 
        className="nptel-widgets-modal-dialog" 
        onClick={(e) => e.stopPropagation()}
      >
        {/* Modal Header */}
        <div className="nptel-modal-header bg-slate-900 text-white flex-between p-4">
          <div className="flex-align-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-blue-600 flex-center text-white">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h3 className="font-bold text-sm">NCIE AI Powered Widgets</h3>
              <p className="text-xxs text-slate-400">Intelligent learning tools for {currentLesson.title}</p>
            </div>
          </div>
          <button 
            type="button" 
            onClick={onClose}
            className="p-1 rounded text-slate-400 hover:text-white hover:bg-slate-800"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Modal Navigation Tabs */}
        <div className="nptel-modal-tab-strip">
          <button
            type="button"
            onClick={() => setActiveTool("explainer")}
            className={`nptel-modal-tab-btn ${activeTool === "explainer" ? "active" : ""}`}
          >
            <Brain className="w-3.5 h-3.5" />
            <span>AI Concept Explainer</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTool("mcq")}
            className={`nptel-modal-tab-btn ${activeTool === "mcq" ? "active" : ""}`}
          >
            <HelpCircle className="w-3.5 h-3.5" />
            <span>Practice MCQ Bot</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTool("flashcards")}
            className={`nptel-modal-tab-btn ${activeTool === "flashcards" ? "active" : ""}`}
          >
            <Layers className="w-3.5 h-3.5" />
            <span>Revision Flashcards</span>
          </button>

          <button
            type="button"
            onClick={() => setActiveTool("credit")}
            className={`nptel-modal-tab-btn ${activeTool === "credit" ? "active" : ""}`}
          >
            <Calculator className="w-3.5 h-3.5" />
            <span>Credit Calculator</span>
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-5 max-h-[65vh] overflow-y-auto">
          {/* TOOL 1: AI Concept Explainer */}
          {activeTool === "explainer" && (
            <div>
              <label className="text-xs font-bold text-slate-700 block mb-1">
                Enter any term or concept to simplify:
              </label>
              <div className="flex gap-2 mb-4">
                <input
                  type="text"
                  value={explainerTopic}
                  onChange={(e) => setExplainerTopic(e.target.value)}
                  placeholder="e.g. Design Thinking, Unit Economics, TRL Levels..."
                  className="input flex-1 text-xs"
                />
                <button
                  type="button"
                  onClick={handleGenerateExplanation}
                  disabled={isGenerating}
                  className="btn btn-primary btn-sm shrink-0"
                >
                  {isGenerating ? (
                    <RefreshCw className="w-3.5 h-3.5 animate-spin mr-1" />
                  ) : (
                    <Sparkles className="w-3.5 h-3.5 mr-1" />
                  )}
                  <span>Explain Concept</span>
                </button>
              </div>

              {explanationResult ? (
                <div className="p-4 bg-blue-50/50 border border-blue-100 rounded-lg text-xs leading-relaxed text-slate-700 whitespace-pre-line">
                  {explanationResult}
                </div>
              ) : (
                <div className="p-4 border border-dashed border-slate-200 rounded-lg text-center text-xs text-slate-500">
                  Click 'Explain Concept' to generate an intelligent AI breakdown formatted for NPTEL revision.
                </div>
              )}
            </div>
          )}

          {/* TOOL 2: Practice MCQ Bot */}
          {activeTool === "mcq" && (
            <div>
              <div className="p-3 bg-amber-50 border border-amber-200 rounded-lg text-xs text-amber-900 mb-4">
                <strong>Practice Mode:</strong> Practice questions to prepare for Week {currentLesson.weekNumber} assignment. These attempts are diagnostic and do not affect your formal grade.
              </div>

              <div className="space-y-4">
                <div className="p-4 border border-slate-200 rounded-lg bg-white">
                  <div className="text-xs font-bold text-slate-800 mb-2">
                    Q1. How does the National Innovation Framework calculate commercialization priority for student patent filings?
                  </div>
                  <div className="space-y-1.5 text-xs text-slate-700">
                    <label className="flex items-center gap-2 p-2 rounded hover:bg-slate-50 cursor-pointer border border-transparent hover:border-slate-200">
                      <input type="radio" name="p-q1" />
                      <span>By prioritizing projects with provisional patent priority and TRL &ge; 4</span>
                    </label>
                    <label className="flex items-center gap-2 p-2 rounded hover:bg-slate-50 cursor-pointer border border-transparent hover:border-slate-200">
                      <input type="radio" name="p-q1" />
                      <span>Based solely on collegiate semester exam marks</span>
                    </label>
                    <label className="flex items-center gap-2 p-2 rounded hover:bg-slate-50 cursor-pointer border border-transparent hover:border-slate-200">
                      <input type="radio" name="p-q1" />
                      <span>Through random lottery selection</span>
                    </label>
                  </div>
                  <div className="mt-3 text-xxs text-emerald-700 bg-emerald-50 p-2 rounded">
                    <strong>Mentor Hint:</strong> Look at the IPR provisions in the NCIE Orientation Guidelines.
                  </div>
                </div>
              </div>
            </div>
          )}

          {/* TOOL 3: Revision Flashcards */}
          {activeTool === "flashcards" && (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              <div className="p-4 rounded-lg border border-slate-200 bg-white shadow-xs">
                <span className="text-xxs font-bold text-blue-600 uppercase tracking-wider block mb-1">Concept 1</span>
                <h4 className="font-bold text-slate-900 text-sm mb-2">Technology Readiness Level (TRL)</h4>
                <p className="text-xs text-slate-600 leading-relaxed">
                  A 9-level measurement system developed by NASA and adopted by India's DST to evaluate the maturity level of a particular technology from basic research (TRL 1) to proven commercial deployment (TRL 9).
                </p>
              </div>

              <div className="p-4 rounded-lg border border-slate-200 bg-white shadow-xs">
                <span className="text-xxs font-bold text-emerald-600 uppercase tracking-wider block mb-1">Concept 2</span>
                <h4 className="font-bold text-slate-900 text-sm mb-2">Best 6 of 8 Rule</h4>
                <p className="text-xs text-slate-600 leading-relaxed">
                  The standard NPTEL/NCIE academic policy where only your top 6 weekly assignment scores are factored into your 25% course assessment score, safeguarding students from unexpected sick days or midterms.
                </p>
              </div>

              <div className="p-4 rounded-lg border border-slate-200 bg-white shadow-xs">
                <span className="text-xxs font-bold text-purple-600 uppercase tracking-wider block mb-1">Concept 3</span>
                <h4 className="font-bold text-slate-900 text-sm mb-2">Unit Economics (CAC vs LTV)</h4>
                <p className="text-xs text-slate-600 leading-relaxed">
                  The direct revenues and costs associated with an individual business model unit. A healthy enterprise maintains Customer Lifetime Value (LTV) at least 3x higher than Customer Acquisition Cost (CAC).
                </p>
              </div>

              <div className="p-4 rounded-lg border border-slate-200 bg-white shadow-xs">
                <span className="text-xxs font-bold text-amber-600 uppercase tracking-wider block mb-1">Concept 4</span>
                <h4 className="font-bold text-slate-900 text-sm mb-2">Provisional Patent Specification</h4>
                <p className="text-xs text-slate-600 leading-relaxed">
                  A preliminary legal document filed with the Indian Patent Office (IPO) that establishes priority date at low cost without complete claims, granting 12 months to submit the complete specification.
                </p>
              </div>
            </div>
          )}

          {/* TOOL 4: AICTE Credit Estimator */}
          {activeTool === "credit" && (
            <div>
              <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-xs text-blue-900 mb-4">
                <strong>Formula:</strong> Consolidated Final Score = <code>0.25 &times; (Best 6 Assignments) + 0.75 &times; (Capstone Defense)</code>. Passing threshold: &ge; 40% in both components.
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1">
                    Best 6 of 8 Assignments Average (%):
                  </label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    value={best6Avg}
                    onChange={(e) => setBest6Avg(Number(e.target.value))}
                    className="input text-xs w-full"
                  />
                </div>

                <div>
                  <label className="text-xs font-bold text-slate-700 block mb-1">
                    Capstone Project & Defense Score (%):
                  </label>
                  <input
                    type="number"
                    min="0"
                    max="100"
                    value={capstoneScore}
                    onChange={(e) => setCapstoneScore(Number(e.target.value))}
                    className="input text-xs w-full"
                  />
                </div>
              </div>

              <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg flex-between">
                <div>
                  <div className="text-xs text-slate-500 font-medium">Estimated Final Score</div>
                  <div className="text-2xl font-black text-slate-900">{finalCalculatedScore}%</div>
                  <div className="text-xxs font-bold text-slate-600 mt-1">
                    {finalCalculatedScore >= 90 ? "Eligible for Elite + Gold Certificate" :
                     finalCalculatedScore >= 75 ? "Eligible for Elite + Silver Certificate" :
                     finalCalculatedScore >= 60 ? "Eligible for Elite Certificate" :
                     finalCalculatedScore >= 40 ? "Eligible for Successfully Completed Certificate" : "Needs improvement"}
                  </div>
                </div>

                <div className="text-right">
                  <div className={`badge ${isCreditEligible ? 'badge-success' : 'badge-warning'}`}>
                    {isCreditEligible ? "2 AICTE Credits Eligible" : "Ineligible (< 40% threshold)"}
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex-between">
          <span className="text-xxs text-slate-500">
            Powered by NCIE Academic AI Engine &bull; Viksit Bharat @2047 Innovation Council
          </span>
          <button type="button" onClick={onClose} className="btn btn-outline btn-sm">
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
